export const rooms = [
  {
    id: 1,
    name: "PREMIUM COTTAGE",
    description:
      "Premium Cottages are cosy and peaceful, making it an ideal retreat for a holiday.The cottages are furnished and designed with thoughtful care and attention.",
    image: "/images/premium-room/p-3.jpg",
    path: "/premiumwh",
    rate: "3500",
    gst: "12%",
    extraBedRate: 600,
    cancel: "Free cancellation 72 hours prior to check in",

    size: "200 square feet",
    capacity: "2 adults + 1 child",
    numberOfRooms: "11",
    extraPerson: "1 Adult or Child",
    occupancy: "2 Adults",
    amenities: [
      { icon: "../images/icon/amenities-img-1.png", lable: "Free Wifi" },
      {
        icon: "../images/icon/amenities-img-3.png",
        lable: "Plush Queen size bed with ergonomic mattress",
      },
      {
        icon: "../images/icon/amenities-img-2.png",
        lable: "LED TV with cable connection",
      },
      { icon: "../images/icon/amenities-img-9.png", lable: "Writing Table" },
      { icon: "../images/icon/amenities-img-7.png", lable: "Hot Water Kettle" },
      {
        icon: "../images/icon/amenities-img-10.png",
        lable: "Shampoo & Shower Gel Dispenser",
      },
    ],
    gallery: [
      "../images/premium-room/p-1.jpg",
      "../images/premium-room/p-2.jpg",
      "../images/premium-room/p-3.jpg",
      "../images/premium-room/p-4.jpg",
      "../images/premium-room/p-5.jpg",
      "../images/premium-room/p-6.jpg",
    ],
  },
  {
    id: 2,
    name: "SUPER DELUXE ROOM",
    description:
      "Every room at Zeenath Taj Garden offers luxury. Enjoy nature views from these super deluxe rooms which will add essence to your stay at Zeenath Taj Gardens.",
    image: "/images/super-deluxe-room/sd-3.jpg",
    path: "/premiumwh",
    rate: "4200",
    gst: "12%",
    extraBedRate: 600,
    cancel: "Free cancellation 72 hours prior to check in",

    size: "260 square feet",
    capacity: "2 adults + 1 child",
    numberOfRooms: "5",
    extraPerson: "1 Adult",
    occupancy: "2 Adults + 1 Child",
    amenities: [
      { icon: "/images/icon/amenities-img-1.png", lable: "Free Wifi" },
      {
        icon: "/images/icon/amenities-img-3.png",
        lable: "Plush Queen size bed with ergonomic mattress",
      },
      {
        icon: "/images/icon/amenities-img-2.png",
        lable: " LED TV with cable connection",
      },
      { icon: "/images/icon/amenities-img-9.png", lable: "Writing Table" },
      { icon: "/images/icon/amenities-img-7.png", lable: "Hot Water Kettle" },
      {
        icon: "/images/icon/amenities-img-10.png",
        lable: "Shampoo & Shower Gel Dispenser",
      },
    ],
    gallery: [
      "/images/super-deluxe-room/sd-1.jpg",
      "/images/super-deluxe-room/sd-2.jpg",
      "/images/super-deluxe-room/sd-3.jpg",
      "/images/super-deluxe-room/sd-4.jpg",
      "/images/super-deluxe-room/sd-5.jpg",
      "/images/super-deluxe-room/sd-6.jpg",
    ],
  },
  {
    id: 3,
    name: "PREMIUM COTTAGE WITH HALL",
    description:
      "Premium Cottage with Hall comes with a large bedroom and attached closed seating area with windows overlooking the garden . All rooms are bath attached and come with LED TV and Free Wifi  and designed with thoughtful care and attention for a relaxing stay amidst the lush green surroundings.",
    image: "/images/premium-wh-room/ph-3.jpg",
    path: "/premiumwh",
    rate: "3900",
    gst: "12%",
    extraBedRate: 600,
    cancel: "Free cancellation 72 hours prior to check in",
    size: "280 square feet",
    capacity: "2 adults + 1 child",
    numberOfRooms: "3",
    extraPerson: "1 Adult",
    occupancy: "2 Adults + 1 Child",
    amenities: [
      { icon: "/images/icon/amenities-img-1.png", lable: "Free Wifi" },
      {
        icon: "/images/icon/amenities-img-3.png",
        lable: "Plush Queen size bed with ergonomic mattress",
      },
      {
        icon: "/images/icon/amenities-img-2.png",
        lable: " LED TV with cable connection",
      },
      { icon: "/images/icon/amenities-img-9.png", lable: "Writing Table" },
      {
        icon: "/images/icon/amenities-img-10.png",
        lable: "Shampoo & Shower Gel Dispenser",
      },
    ],
    gallery: [
      "/images/premium-wh-room/ph-1.jpg",
      "/images/premium-wh-room/ph-2.jpg",
      "/images/premium-wh-room/ph-3.jpg",
      "/images/premium-wh-room/ph-4.jpg",
    ],
  },
  {
    id: 4,
    name: "DELUXE CHALET",
    description:
      "Deluxe Chalet features a spacious bedroom and a Verandah deck with a serene view of the garden and  is fully equipped with ameneties to make your stay pleasant and comfortable. The private sitout with a relaxing lounge chair paired with rattan cane bucket swing make it a a perfect setting for a lazy holiday!",
    image: "/images/deluxe-chalet-room/dc-5.jpg",
    path: "/premiumwh",
    rate: "5200",
    gst: "12%",
    extraBedRate: 600,
    cancel: "Free cancellation 72 hours prior to check in",

    size: "340 square feet",
    capacity: "2 adults + 1 child",
    numberOfRooms: "8",
    extraPerson: "1 Adult",
    occupancy: "2 Adults + 1 Child",
    amenities: [
      { icon: "/images/icon/amenities-img-1.png", lable: "Free Wifi" },
      {
        icon: "/images/icon/amenities-img-3.png",
        lable: "Plush King size bed with ergonomic mattress",
      },
      {
        icon: "/images/icon/amenities-img-2.png",
        lable: " 32'LCD TV with cable connection",
      },
      {
        icon: "/images/icon/diningaboutimg-2.png",
        lable: "Openable French Door",
      },
      { icon: "/images/icon/amenities-img-9.png", lable: "Writing Table" },
      { icon: "/images/icon/amenities-img-7.png", lable: "Hot Water Kettle" },
      { icon: "/images/icon/amenities-img-4.png", lable: "2 Seater Sofa" },
      {
        icon: "/images/icon/amenities-img-12.png",
        lable: "Rattan Cane Bucket Swing",
      },
      { icon: "/images/icon/amenities-img-6.png", lable: "Lounge Deck Chair" },
      {
        icon: "/images/icon/amenities-img-10.png",
        lable: "Shampoo & Shower Gel Dispenser",
      },
    ],
    gallery: [
      "/src/images/deluxe-chalet-room/dc-1.jpg",
      "/images/deluxe-chalet-room/dc-2.jpg",
      "/images/deluxe-chalet-room/dc-3.jpg",
      "/images/deluxe-chalet-room/dc-4.jpg",
      "/images/deluxe-chalet-room/dc-5.jpg",
      "/images/deluxe-chalet-room/dc-6.jpg",
    ],
  },
  {
    id: 5,
    name: "SUPER DELUXE SUITE",
    description:
      "Well appointed deluxe rooms & luxurious suites with fascinating views & amenities perfect for your comfortable stay.Thoughtfully constructed suite to make your stay more pleasant at Zeenath Taj Garden.",
    image: "/images/super-deluxe-suite/sds-1.png",
    path: "/premiumwh",
    rate: "5200",
    gst: "12%",
    extraBedRate: 600,
    cancel: "Free cancellation 72 hours prior to check in",

    size: "380 square feet",
    capacity: "2 adults + 1 child",
    numberOfRooms: "1",
    extraPerson: "1 Adult",
    occupancy: "4 Adults + 1 Child",
    amenities: [
      { icon: "/images/icon/amenities-img-1.png", lable: "Free Wifi" },
      {
        icon: "/images/icon/amenities-img-3.png",
        lable: "Plush Queen size bed with ergonomic mattress",
      },
      {
        icon: "/images/icon/amenities-img-2.png",
        lable: " LED TV with cable connection",
      },
      { icon: "/images/icon/amenities-img-9.png", lable: "Writing Table" },
      { icon: "/images/icon/amenities-img-7.png", lable: "Hot Water Kettle" },
      {
        icon: "/images/icon/amenities-img-10.png",
        lable: "Shampoo & Shower Gel Dispenser",
      },
    ],
    gallery: [
      "/images/premium-room/p-1.jpg",
      "/images/premium-room/p-2.jpg",
      "/images/premium-room/p-3.jpg",
      "/images/premium-room/p-4.jpg",
      "/images/premium-room/p-5.jpg",
      "/images/premium-room/p-6.jpg",
    ],
  },
  {
    id: 6,
    name: "DELUXE CHALET SUITE",
    description:
      "Well appointed deluxe rooms & luxurious suites with fascinating views & amenities perfect for your comfortable stay.Thoughtfully constructed suite to make your stay more pleasant at Zeenath Taj Garden.",
    image: "/images/deluxe-chalet-suite/dcs-1.jpg",
    path: "/premiumwh",
    rate: "7200",
    gst: "12%",
    extraBedRate: 600,
    cancel: "Free cancellation 72 hours prior to check in",

    size: "460 square feet",
    capacity: "2 adults + 1 child",
    numberOfRooms: "1",
    extraPerson: "1 Adult",
    occupancy: "4 Adults + 1 Child",
    amenities: [
      { icon: "/images/icon/amenities-img-1.png", lable: "Free Wifi" },
      {
        icon: "/images/icon/amenities-img-3.png",
        lable: "Plush King size bed with ergonomic mattress",
      },
      {
        icon: "/images/icon/amenities-img-3.png",
        lable: "Plush Queen size bed with ergonomic mattress",
      },
      {
        icon: "/images/icon/amenities-img-2.png",
        lable: " 32'LCD TV with cable connection",
      },
      {
        icon: "/images/icon/diningaboutimg-2.png",
        lable: "Openable French Door",
      },
      { icon: "/images/icon/amenities-img-9.png", lable: "Writing Table" },
      { icon: "/images/icon/amenities-img-7.png", lable: "Hot Water Kettle" },
      { icon: "/images/icon/amenities-img-4.png", lable: "2 Seater Sofa" },
      {
        icon: "/images/icon/amenities-img-12.png",
        lable: "Bucket Swing in Balcony",
      },
      {
        icon: "/images/icon/amenities-img-10.png",
        lable: "Shampoo & Shower Gel Dispenser",
      },
    ],
    gallery: [
      "/images/deluxe-chalet-room/dc-1.jpg",
      "/images/deluxe-chalet-room/dc-2.jpg",
      "/images/deluxe-chalet-room/dc-3.jpg",
      "/images/deluxe-chalet-room/dc-4.jpg",
      "/images/deluxe-chalet-room/dc-5.jpg",
      "/images/deluxe-chalet-room/dc-6.jpg",
    ],
  },
  {
    id: 7,
    name: "SUPER DELUXE COTTAGE",
    description:
      "Premium Cottages feature a queen size bed with colourful furnishings that add a cozy  touch to the interiors for a relaxing stay . All rooms are bath attached with LED TV and Free Wifi.Wake up to the chirping of birds  to refresh your mind for that well needed break.",
    image: "/images/main-image/sdc-main.png",
    path: "/room/7",
    rate: "8200",
    gst: "12%",
    extraBedRate: 600,
    cancel: "Free cancellation 72 hours prior to check in",

    size: "200 square feet",
    capacity: "2 adults + 1 child",
    numberOfRooms: "11",
    extraPerson: "1 Adult or Child",
    occupancy: "2 Adults",
    amenities: [
      { icon: "/images/icon/amenities-img-1.png", lable: "Free Wifi" },
      {
        icon: "/images/icon/amenities-img-3.png",
        lable: "Plush Queen size bed with ergonomic mattress",
      },
      {
        icon: "/images/icon/amenities-img-2.png",
        lable: "LED TV with cable connection",
      },
      { icon: "/images/icon/amenities-img-9.png", lable: "Writing Table" },
      { icon: "/images/icon/amenities-img-7.png", lable: "Hot Water Kettle" },
      {
        icon: "/images/icon/amenities-img-10.png",
        lable: "Shampoo & Shower Gel Dispenser",
      },
    ],
    gallery: [
      "/images/premium-room/p-1.jpg",
      "/images/premium-room/p-2.jpg",
      "/images/premium-room/p-3.jpg",
      "/images/premium-room/p-4.jpg",
      "/images/premium-room/p-5.jpg",
      "/images/premium-room/p-6.jpg",
    ],
  },
];
